var storeData = [
    {id:1,
    name: "Cat Fuzz",
    price: 123.12,
    desc: "Furry Fuzzy screeches",
    image:"images/01.jpg"},
    {id:2,
    name: "Tweedle Echo",
    price:132.32,
    desc: "If I've said it once I've said twice...",
    image:"images/02.jpg"},
    {id:3,
    name: "Multiplex Echo",
    desc:"",
    price:213.21,
    image:"images/03.jpg"},
    {id:4,
    name: "Shifty thing",
    desc:"5 and 6 stages of smooth shiftyness.",
    price:199.99,
    image:"images/04.jpg"},
    {id:5,
    name: "Shifty thing",
    desc:"5 and 6 stages of smooth shiftyness.",
    price:199.99,
    image:"images/05.jpg"},
    {id:6,
    name: "Delay thing",
    desc:"Echoing delay thing with extra knobiness.",
    price:199.99,
    image:"images/06.jpg"},
    {id:7,
    name: "Furr Face Fuzz",
    desc:"Furr Face suzz with shag carpet noise.",
    price:199.99,
    image:"images/07.jpg"},
    {id:8,
    name: "Super Boosty",
    desc:"Super Boostiness with get louder knob.",
    price:120.99,
    image:"images/08.jpg"},
    {id:9,
    name: "Car Crash",
    desc:"Car Crash Fuzz, with two transistor fuzz action.",
    price:156.99,
    image:"images/09.jpg"}
];